steps:
  - label: ":shell: Shellcheck"
    plugins:
      kubernetes:
        containers:
        - image: docker.io/bmo/helloworld-go
          env:
          - name: TARGET
            value: "Go Sample v1"
