steps:
- name: build image
  agents:
    kubernetes: true
  plugins:
  - kubernetes:
      containers:
      - image: gcr.io/kaniko-project/executor:latest
        command: executor
        args:
        - --dockerfile=Dockerfile
        - --context=.
        - --destination=ttl.sh/demo:10m
