env:
  # Some of these are end-to-end integration tests that require a Docker
  # registry to run. We boot one up in the .hooks/pre-command, and then use that
  # registry for doing all the push/pull testing.
  IMAGE_REPO: "localhost:5005/docker-compose-test"

steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files:
          - hooks/**
          - lib/**
          - commands/**

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v3.0.0:
        id: docker-compose

  - label: ":bash: Tests"
    plugins:
      ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        run: tests
        command: ["bats", "tests", "tests/v2"]
